#include "track_strategy.h"

static const track_mode_params_t g_mode_params[] = {
    {TRACK_MODE_STRAIGHT,
     FUZZY_STRAIGHT_BASE_KP, FUZZY_STRAIGHT_BASE_KI, FUZZY_STRAIGHT_BASE_KD,
     FUZZY_STRAIGHT_KP_LIMIT, FUZZY_STRAIGHT_KI_LIMIT, FUZZY_STRAIGHT_KD_LIMIT,
     FUZZY_STRAIGHT_STEER_LIMIT_US, FUZZY_STRAIGHT_RATE_LIMIT_US, FUZZY_STRAIGHT_SPEED_MM_S},
    {TRACK_MODE_NORMAL_CURVE,
     FUZZY_NORMAL_BASE_KP, FUZZY_NORMAL_BASE_KI, FUZZY_NORMAL_BASE_KD,
     FUZZY_NORMAL_KP_LIMIT, FUZZY_NORMAL_KI_LIMIT, FUZZY_NORMAL_KD_LIMIT,
     FUZZY_NORMAL_STEER_LIMIT_US, FUZZY_NORMAL_RATE_LIMIT_US, FUZZY_NORMAL_SPEED_MM_S},
    {TRACK_MODE_SHARP_CURVE,
     FUZZY_SHARP_BASE_KP, FUZZY_SHARP_BASE_KI, FUZZY_SHARP_BASE_KD,
     FUZZY_SHARP_KP_LIMIT, FUZZY_SHARP_KI_LIMIT, FUZZY_SHARP_KD_LIMIT,
     FUZZY_SHARP_STEER_LIMIT_US, FUZZY_SHARP_RATE_LIMIT_US, FUZZY_SHARP_SPEED_MM_S},
    {TRACK_MODE_CROSSING,
     FUZZY_NORMAL_BASE_KP, 0, FUZZY_NORMAL_BASE_KD,
     FUZZY_NORMAL_KP_LIMIT, 0, FUZZY_NORMAL_KD_LIMIT,
     FUZZY_NORMAL_STEER_LIMIT_US, FUZZY_NORMAL_RATE_LIMIT_US, 260},
    {TRACK_MODE_OMEGA,
     FUZZY_OMEGA_BASE_KP, FUZZY_OMEGA_BASE_KI, FUZZY_OMEGA_BASE_KD,
     FUZZY_OMEGA_KP_LIMIT, FUZZY_OMEGA_KI_LIMIT, FUZZY_OMEGA_KD_LIMIT,
     FUZZY_OMEGA_STEER_LIMIT_US, FUZZY_OMEGA_RATE_LIMIT_US, FUZZY_OMEGA_SPEED_MM_S},
    {TRACK_MODE_HEX_LOOP,
     FUZZY_HEX_BASE_KP, FUZZY_HEX_BASE_KI, FUZZY_HEX_BASE_KD,
     FUZZY_HEX_KP_LIMIT, FUZZY_HEX_KI_LIMIT, FUZZY_HEX_KD_LIMIT,
     FUZZY_HEX_STEER_LIMIT_US, FUZZY_HEX_RATE_LIMIT_US, FUZZY_HEX_SPEED_MM_S},
    {TRACK_MODE_TRANSITION,
     FUZZY_TRANSITION_BASE_KP, FUZZY_TRANSITION_BASE_KI, FUZZY_TRANSITION_BASE_KD,
     FUZZY_TRANSITION_KP_LIMIT, FUZZY_TRANSITION_KI_LIMIT, FUZZY_TRANSITION_KD_LIMIT,
     FUZZY_TRANSITION_STEER_LIMIT_US, FUZZY_TRANSITION_RATE_LIMIT_US, FUZZY_TRANSITION_SPEED_MM_S},
    {TRACK_MODE_WALL,
     FUZZY_WALL_BASE_KP, FUZZY_WALL_BASE_KI, FUZZY_WALL_BASE_KD,
     FUZZY_WALL_KP_LIMIT, FUZZY_WALL_KI_LIMIT, FUZZY_WALL_KD_LIMIT,
     FUZZY_WALL_STEER_LIMIT_US, FUZZY_WALL_RATE_LIMIT_US, FUZZY_WALL_SPEED_MM_S},
    {TRACK_MODE_CYLINDER,
     FUZZY_CYLINDER_BASE_KP, FUZZY_CYLINDER_BASE_KI, FUZZY_CYLINDER_BASE_KD,
     FUZZY_CYLINDER_KP_LIMIT, FUZZY_CYLINDER_KI_LIMIT, FUZZY_CYLINDER_KD_LIMIT,
     FUZZY_CYLINDER_STEER_LIMIT_US, FUZZY_CYLINDER_RATE_LIMIT_US, FUZZY_CYLINDER_SPEED_MM_S},
    {TRACK_MODE_SEESAW,
     FUZZY_SEESAW_BASE_KP, FUZZY_SEESAW_BASE_KI, FUZZY_SEESAW_BASE_KD,
     FUZZY_SEESAW_KP_LIMIT, FUZZY_SEESAW_KI_LIMIT, FUZZY_SEESAW_KD_LIMIT,
     FUZZY_SEESAW_STEER_LIMIT_US, FUZZY_SEESAW_RATE_LIMIT_US, FUZZY_SEESAW_SPEED_MM_S},
    {TRACK_MODE_LINE_LOST,
     FUZZY_RECOVERY_BASE_KP, 0, FUZZY_RECOVERY_BASE_KD,
     0, 0, 0,
     90, 60, 0},
    {TRACK_MODE_RECOVERY,
     FUZZY_RECOVERY_BASE_KP, FUZZY_RECOVERY_BASE_KI, FUZZY_RECOVERY_BASE_KD,
     FUZZY_RECOVERY_KP_LIMIT, FUZZY_RECOVERY_KI_LIMIT, FUZZY_RECOVERY_KD_LIMIT,
     FUZZY_RECOVERY_STEER_LIMIT_US, FUZZY_RECOVERY_RATE_LIMIT_US, FUZZY_RECOVERY_SPEED_MM_S}
};

const track_mode_params_t *track_strategy_mode_params(track_mode_t mode)
{
    u16 index;
    for (index = 0u; index < (u16)(sizeof(g_mode_params) / sizeof(g_mode_params[0])); index++) {
        if (g_mode_params[index].mode == mode) {
            return &g_mode_params[index];
        }
    }
    return &g_mode_params[0];
}

s16 track_strategy_target_speed_for_mode(track_mode_t mode)
{
    return track_strategy_mode_params(mode)->target_speed_mm_s;
}

s16 track_strategy_target_speed(surface_state_t surface)
{
    if (surface == SURFACE_WALL) return SPEED_LIMIT_WALL_MM_S;
    if (surface == SURFACE_TRANSITION_UP) return SPEED_LIMIT_TRANSITION_MM_S;
    return SPEED_LIMIT_GROUND_MM_S;
}
