#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_TEST_MODE 1
#define APP_MANUAL_ARM_REQUIRED 1
#define FYZW_USE_LQ_OFFICIAL_LIB 0

#define FYZW_MAIN_FOSC_HZ 40000000ul

#define TASK_FAST_SENSOR_PERIOD_MS 1u
#define TASK_CONTROL_PERIOD_MS 2u
#define TASK_ADHESION_PERIOD_MS 5u
#define TASK_SPEED_PERIOD_MS 10u
#define TASK_TRACK_PERIOD_MS 20u
#define TASK_HEALTH_PERIOD_MS 50u
#define TASK_UI_TELEMETRY_PERIOD_MS 100u

#define DRIVE_SAFE_ZERO 0
#define DRIVE_PWM_FREQ_HZ 12500u
#define STEERING_CENTER_US 1510u
#define STEERING_SAFE_CENTER_US STEERING_CENTER_US
#define STEERING_MIN_PULSE_US 1000u
#define STEERING_MAX_PULSE_US 2000u
#define STEERING_MAX_OFFSET_US 500
#define STEERING_PWM_FREQ_HZ 50u
#define DRIVE_LIMIT_ABS 1000
#define CONTROL_OVERRUN_LIMIT_MS 6u

#define SUCTION_PROTOCOL_UNKNOWN 0
#define SUCTION_PROTOCOL_RC_PULSE_US 1
#define SUCTION_HW_VERIFIED 0
#define SUCTION_BENCH_TEST_ENABLE 0
#define SUCTION_PROTOCOL_MODE SUCTION_PROTOCOL_RC_PULSE_US
#define SUCTION_SAFE_OFF_NATIVE 0
#define SUCTION_IDLE_NATIVE 0
#define SUCTION_PRECHARGE_NATIVE 0
#define SUCTION_HOLD_NATIVE 0
#define SUCTION_BOOST_NATIVE 0
#define SUCTION_EMERGENCY_HOLD_NATIVE 0
#define SUCTION_RC_MIN_US 1000u
#define SUCTION_RC_MAX_US 2000u
#define SUCTION_RC_RECOMMENDED_HZ 50u
#define SUCTION_RAMP_UP_PER_S 0
#define SUCTION_RAMP_DOWN_PER_S 0
#define SUCTION_BOOST_TIMEOUT_MS 0u
#define SUCTION_COOLDOWN_MS 0u
#define SUCTION_FEEDBACK_AVAILABLE 0

#define LINE_QUALITY_MIN 200u
#define SENSOR_STALE_TIMEOUT_MS 50u
#define WALL_CONFIRM_TIME_MS 200u
#define GROUND_CONFIRM_TIME_MS 300u
#define TRANSITION_TIMEOUT_MS 3000u
#define PRECHARGE_MIN_TIME_MS 100u
#define TRANSITION_MIN_PROGRESS_MM 40l
#define GROUND_PITCH_MAX_CDEG 1200
#define TRANSITION_PITCH_CDEG 2000
#define WALL_PITCH_CDEG 6000
#define ADHESION_RISK_LIMIT 700u
#define SPEED_LIMIT_GROUND_MM_S 500
#define SPEED_LIMIT_PRECHARGE_MM_S 120
#define SPEED_LIMIT_TRANSITION_MM_S 80
#define SPEED_LIMIT_WALL_MM_S 100

#endif
