#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_TEST_MODE 1
#define APP_MANUAL_ARM_REQUIRED 1
#define FYZW_USE_LQ_OFFICIAL_LIB 0

#define FYZW_MAIN_FOSC_HZ 40000000ul

#define TASK_FAST_SENSOR_PERIOD_MS 1u
#define TASK_CONTROL_PERIOD_MS 2u
#define TASK_ADHESION_PERIOD_MS 5u
#define TASK_SPEED_PERIOD_MS 10u
#define TASK_TRACK_PERIOD_MS 20u
#define TASK_HEALTH_PERIOD_MS 50u
#define TASK_UI_TELEMETRY_PERIOD_MS 100u

#define DRIVE_SAFE_ZERO 0
#define DRIVE_PWM_FREQ_HZ 12500u
#define STEERING_CENTER_US 1510u
#define STEERING_SAFE_CENTER_US STEERING_CENTER_US
#define STEERING_MIN_PULSE_US 1000u
#define STEERING_MAX_PULSE_US 2000u
#define STEERING_MAX_OFFSET_US 500
#define STEERING_PWM_FREQ_HZ 50u
#define DRIVE_LIMIT_ABS 1000
#define CONTROL_OVERRUN_LIMIT_MS 6u

#define FUZZY_E_SCALE 1000
#define FUZZY_DE_SCALE 1000
#define FUZZY_UPDATE_PERIOD_MS 10u
#define FUZZY_KP_SCALE 100
#define FUZZY_KI_SCALE 100
#define FUZZY_KD_SCALE 100
#define FUZZY_PID_OUTPUT_SCALE 1000l
#define FUZZY_KP_MIN 0
#define FUZZY_KP_MAX 600
#define FUZZY_KI_MIN 0
#define FUZZY_KI_MAX 80
#define FUZZY_KD_MIN 0
#define FUZZY_KD_MAX 500
#define TRACK_MODE_DEBOUNCE_COUNT 3u
#define TRACK_MODE_MIN_DWELL_MS 60u
#define TRACK_LINE_LOST_QUALITY_MIN LINE_QUALITY_MIN
#define TRACK_STRAIGHT_ERROR_MAX 80
#define TRACK_STRAIGHT_RATE_MAX 60
#define TRACK_NORMAL_CURVE_ERROR_MAX 260
#define TRACK_SHARP_CURVE_ERROR_MIN 420
#define TRACK_OMEGA_RATE_MIN 340
#define TRACK_CROSS_QUALITY_MIN 900u

#define FUZZY_STRAIGHT_BASE_KP 115
#define FUZZY_STRAIGHT_BASE_KI 4
#define FUZZY_STRAIGHT_BASE_KD 70
#define FUZZY_STRAIGHT_KP_LIMIT 28
#define FUZZY_STRAIGHT_KI_LIMIT 4
#define FUZZY_STRAIGHT_KD_LIMIT 22
#define FUZZY_STRAIGHT_STEER_LIMIT_US 160
#define FUZZY_STRAIGHT_RATE_LIMIT_US 24
#define FUZZY_STRAIGHT_SPEED_MM_S SPEED_LIMIT_GROUND_MM_S

#define FUZZY_NORMAL_BASE_KP 155
#define FUZZY_NORMAL_BASE_KI 0
#define FUZZY_NORMAL_BASE_KD 95
#define FUZZY_NORMAL_KP_LIMIT 44
#define FUZZY_NORMAL_KI_LIMIT 0
#define FUZZY_NORMAL_KD_LIMIT 34
#define FUZZY_NORMAL_STEER_LIMIT_US 240
#define FUZZY_NORMAL_RATE_LIMIT_US 30
#define FUZZY_NORMAL_SPEED_MM_S 360

#define FUZZY_SHARP_BASE_KP 220
#define FUZZY_SHARP_BASE_KI 0
#define FUZZY_SHARP_BASE_KD 150
#define FUZZY_SHARP_KP_LIMIT 70
#define FUZZY_SHARP_KI_LIMIT 0
#define FUZZY_SHARP_KD_LIMIT 52
#define FUZZY_SHARP_STEER_LIMIT_US 360
#define FUZZY_SHARP_RATE_LIMIT_US 42
#define FUZZY_SHARP_SPEED_MM_S 210

#define FUZZY_OMEGA_BASE_KP 240
#define FUZZY_OMEGA_BASE_KI 0
#define FUZZY_OMEGA_BASE_KD 170
#define FUZZY_OMEGA_KP_LIMIT 78
#define FUZZY_OMEGA_KI_LIMIT 0
#define FUZZY_OMEGA_KD_LIMIT 58
#define FUZZY_OMEGA_STEER_LIMIT_US 380
#define FUZZY_OMEGA_RATE_LIMIT_US 36
#define FUZZY_OMEGA_SPEED_MM_S 180

#define FUZZY_HEX_BASE_KP 195
#define FUZZY_HEX_BASE_KI 0
#define FUZZY_HEX_BASE_KD 160
#define FUZZY_HEX_KP_LIMIT 58
#define FUZZY_HEX_KI_LIMIT 0
#define FUZZY_HEX_KD_LIMIT 54
#define FUZZY_HEX_STEER_LIMIT_US 320
#define FUZZY_HEX_RATE_LIMIT_US 28
#define FUZZY_HEX_SPEED_MM_S 240

#define FUZZY_TRANSITION_BASE_KP 150
#define FUZZY_TRANSITION_BASE_KI 0
#define FUZZY_TRANSITION_BASE_KD 165
#define FUZZY_TRANSITION_KP_LIMIT 36
#define FUZZY_TRANSITION_KI_LIMIT 0
#define FUZZY_TRANSITION_KD_LIMIT 60
#define FUZZY_TRANSITION_STEER_LIMIT_US 220
#define FUZZY_TRANSITION_RATE_LIMIT_US 24
#define FUZZY_TRANSITION_SPEED_MM_S SPEED_LIMIT_TRANSITION_MM_S

#define FUZZY_WALL_BASE_KP 190
#define FUZZY_WALL_BASE_KI 0
#define FUZZY_WALL_BASE_KD 170
#define FUZZY_WALL_KP_LIMIT 50
#define FUZZY_WALL_KI_LIMIT 0
#define FUZZY_WALL_KD_LIMIT 58
#define FUZZY_WALL_STEER_LIMIT_US 260
#define FUZZY_WALL_RATE_LIMIT_US 24
#define FUZZY_WALL_SPEED_MM_S SPEED_LIMIT_WALL_MM_S

#define FUZZY_CYLINDER_BASE_KP 230
#define FUZZY_CYLINDER_BASE_KI 0
#define FUZZY_CYLINDER_BASE_KD 180
#define FUZZY_CYLINDER_KP_LIMIT 70
#define FUZZY_CYLINDER_KI_LIMIT 0
#define FUZZY_CYLINDER_KD_LIMIT 64
#define FUZZY_CYLINDER_STEER_LIMIT_US 330
#define FUZZY_CYLINDER_RATE_LIMIT_US 30
#define FUZZY_CYLINDER_SPEED_MM_S 190

#define FUZZY_SEESAW_BASE_KP 145
#define FUZZY_SEESAW_BASE_KI 0
#define FUZZY_SEESAW_BASE_KD 120
#define FUZZY_SEESAW_KP_LIMIT 32
#define FUZZY_SEESAW_KI_LIMIT 0
#define FUZZY_SEESAW_KD_LIMIT 42
#define FUZZY_SEESAW_STEER_LIMIT_US 210
#define FUZZY_SEESAW_RATE_LIMIT_US 18
#define FUZZY_SEESAW_SPEED_MM_S 160

#define FUZZY_RECOVERY_BASE_KP 120
#define FUZZY_RECOVERY_BASE_KI 0
#define FUZZY_RECOVERY_BASE_KD 90
#define FUZZY_RECOVERY_KP_LIMIT 26
#define FUZZY_RECOVERY_KI_LIMIT 0
#define FUZZY_RECOVERY_KD_LIMIT 28
#define FUZZY_RECOVERY_STEER_LIMIT_US 180
#define FUZZY_RECOVERY_RATE_LIMIT_US 20
#define FUZZY_RECOVERY_SPEED_MM_S 120

#define SUCTION_PROTOCOL_UNKNOWN 0
#define SUCTION_PROTOCOL_RC_PULSE_US 1
#define SUCTION_HW_VERIFIED 0
#define SUCTION_BENCH_TEST_ENABLE 0
#define SUCTION_PROTOCOL_MODE SUCTION_PROTOCOL_RC_PULSE_US
#define SUCTION_SAFE_OFF_NATIVE 0
#define SUCTION_IDLE_NATIVE 0
#define SUCTION_PRECHARGE_NATIVE 0
#define SUCTION_HOLD_NATIVE 0
#define SUCTION_BOOST_NATIVE 0
#define SUCTION_EMERGENCY_HOLD_NATIVE 0
#define SUCTION_RC_MIN_US 1000u
#define SUCTION_RC_MAX_US 2000u
#define SUCTION_RC_RECOMMENDED_HZ 50u
#define SUCTION_RAMP_UP_PER_S 0
#define SUCTION_RAMP_DOWN_PER_S 0
#define SUCTION_BOOST_TIMEOUT_MS 0u
#define SUCTION_COOLDOWN_MS 0u
#define SUCTION_FEEDBACK_AVAILABLE 0

#define LINE_QUALITY_MIN 200u
#define SENSOR_STALE_TIMEOUT_MS 50u
#define WALL_CONFIRM_TIME_MS 200u
#define GROUND_CONFIRM_TIME_MS 300u
#define TRANSITION_TIMEOUT_MS 3000u
#define PRECHARGE_MIN_TIME_MS 100u
#define TRANSITION_MIN_PROGRESS_MM 40l
#define GROUND_PITCH_MAX_CDEG 1200
#define TRANSITION_PITCH_CDEG 2000
#define WALL_PITCH_CDEG 6000
#define ADHESION_RISK_LIMIT 700u
#define SPEED_LIMIT_GROUND_MM_S 500
#define SPEED_LIMIT_PRECHARGE_MM_S 120
#define SPEED_LIMIT_TRANSITION_MM_S 80
#define SPEED_LIMIT_WALL_MM_S 100

#endif
