#include "app_params.h"
#include "app_config.h"

static const app_param_entry_t g_params[] = {
    {"FAN_ESC_PHYSICAL_OUTPUT_ENABLE", FAN_ESC_PHYSICAL_OUTPUT_ENABLE, "bool", "0 or 1", "locked", "0 keeps P2.2/PWM2P_3 electrically off"},
    {"WALL_RUN_ENABLE", WALL_RUN_ENABLE, "bool", "0 or 1", "locked", "0 keeps real C251 wall states disabled"},
    {"FAN_PWM_FREQ_HZ", FAN_PWM_FREQ_HZ, "Hz", "ESC protocol dependent", "bench-only", "RC ESC default is 50 Hz"},
    {"FAN_ESC_MIN_US", FAN_ESC_MIN_US, "us", "ESC pulse", "bench-only", "arm/min pulse"},
    {"FAN_ESC_MAX_US", FAN_ESC_MAX_US, "us", "ESC pulse", "bench-only", "max command clamp"},
    {"FAN_PRECHARGE_US", FAN_PRECHARGE_US, "us", "ESC pulse", "bench-only", "precharge request; physical output remains disabled"},
    {"FAN_HOLD_US", FAN_HOLD_US, "us", "ESC pulse", "bench-only", "hold request; physical output remains disabled"},
    {"FAN_BOOST_US", FAN_BOOST_US, "us", "ESC pulse", "bench-only", "boost request; physical output remains disabled"},
    {"FAN_PRECHARGE_TIME_MS", FAN_PRECHARGE_TIME_MS, "ms", "state dwell", "software", "precharge dwell before transition-up confirmation"},
    {"ROUTE_EVENT_SOURCE_DEFAULT", ROUTE_EVENT_SOURCE_DEFAULT, "enum", "0 none 1 host 2 manual 3 progress", "software", "real C251 default is no automatic route event"},
    {"ROUTE_PROGRESS_SCRIPT_ENABLE", ROUTE_PROGRESS_SCRIPT_ENABLE, "bool", "0 or 1", "bench-tune", "enable only after encoder distances are measured"},
    {"ROUTE_WALL_APPROACH_DISTANCE_MM", ROUTE_WALL_APPROACH_DISTANCE_MM, "mm", "0 disables", "bench-tune", "distance to start wall approach event"},
    {"ROUTE_WALL_EXIT_DISTANCE_MM", ROUTE_WALL_EXIT_DISTANCE_MM, "mm", "0 disables", "bench-tune", "distance where progress wall approach expires"},
    {"ROUTE_FINISH_DISTANCE_MM", ROUTE_FINISH_DISTANCE_MM, "mm", "0 disables", "bench-tune", "distance to finish event after ground recovery"},
    {"SUCTION_HW_VERIFIED", SUCTION_HW_VERIFIED, "bool", "0 or 1", "legacy locked", "legacy negative-pressure gate remains 0"},
    {"SUCTION_SAFE_OFF_NATIVE", SUCTION_SAFE_OFF_NATIVE, "native", "legacy", "locked", "historical path remains off"},
    {"TASK_CONTROL_PERIOD_MS", TASK_CONTROL_PERIOD_MS, "ms", "timer dependent", "unverified", "overrun changes stability"},
    {"LINE_DIRECTION_SIGN", LINE_DIRECTION_SIGN, "sign", "+1 or -1", "bench-tune", "wrong sign turns away from the line"},
    {"LINE_VALID_SUM_MIN", LINE_VALID_SUM_MIN, "adc_norm_sum", "5LC calibration dependent", "bench-tune", "wrong threshold causes false line loss"},
    {"LINE_LOST_QUALITY_MIN", LINE_LOST_QUALITY_MIN, "adc_norm_sum", "5LC calibration dependent", "bench-tune", "wrong threshold causes false line loss"},
    {"LINE_FILTER_ALPHA", LINE_FILTER_ALPHA, "fixed_ratio", "0..LINE_FILTER_DENOM", "bench-tune", "too high delays steering"},
    {"STEERING_LEFT_CENTER_US", STEERING_LEFT_CENTER_US, "us", "servo pulse", "bench-tune", "wrong center causes mechanical bias"},
    {"STEERING_RIGHT_CENTER_US", STEERING_RIGHT_CENTER_US, "us", "servo pulse", "bench-tune", "wrong center causes mechanical bias"},
    {"STEERING_LEFT_SIGN", STEERING_LEFT_SIGN, "sign", "+1 or -1", "bench-tune", "wrong sign reverses left servo response"},
    {"STEERING_RIGHT_SIGN", STEERING_RIGHT_SIGN, "sign", "+1 or -1", "bench-tune", "wrong sign reverses right servo response"},
    {"SPEED_KP", SPEED_KP, "gain", "fixed point /100", "bench-tune", "too high causes wheel oscillation"},
    {"SPEED_KI", SPEED_KI, "gain", "fixed point /100", "bench-tune", "too high causes slow windup"},
    {"SPEED_OUTPUT_LIMIT", SPEED_OUTPUT_LIMIT, "native", "low-power default", "bench-tune", "do not raise before off-ground test"},
    {"SPEED_ACCEL_LIMIT", SPEED_ACCEL_LIMIT, "native_per_tick", "low-power default", "bench-tune", "too high causes step torque"},
    {"DIFF_TURN_SIGN", DIFF_TURN_SIGN, "sign", "+1 or -1", "bench-tune", "wrong sign turns away from the line"},
    {"DIFF_TURN_DELTA_LIMIT_MM_S", DIFF_TURN_DELTA_LIMIT_MM_S, "mm_s", "low-power default", "bench-tune", "turn delta clamp before left/right mix"},
    {"DIFF_TARGET_SPEED_LIMIT_MM_S", DIFF_TARGET_SPEED_LIMIT_MM_S, "mm_s", "low-power default", "bench-tune", "left/right target clamp"},
    {"GROUND_STEERING_KP", GROUND_STEERING_KP, "gain", "fixed point", "bench-tune", "straight-line first tuning item"},
    {"GROUND_STEERING_KD", GROUND_STEERING_KD, "gain", "fixed point", "bench-tune", "damping for ground line tracking"},
    {"FUZZY_ENABLE", FUZZY_ENABLE, "bool", "0 or 1", "bench-tune", "enable only after base PD tracks"},
    {"GROUND_STRAIGHT_SPEED_MM_S", GROUND_STRAIGHT_SPEED_MM_S, "mm_s", "low-power default", "bench-tune", "do not treat as race-ready speed"},
    {"GROUND_CURVE_SPEED_MM_S", GROUND_CURVE_SPEED_MM_S, "mm_s", "low-power default", "bench-tune", "curve speed"},
    {"SHARP_CURVE_SPEED_MM_S", SHARP_CURVE_SPEED_MM_S, "mm_s", "low-power default", "bench-tune", "sharp/omega speed"},
    {"TRANSITION_SPEED_MM_S", TRANSITION_SPEED_MM_S, "mm_s", "low-power default", "locked", "not wall permission"},
    {"WALL_SPEED_MM_S", WALL_SPEED_MM_S, "mm_s", "software only", "locked", "not wall permission"},
    {"IMU_PITCH_SIGN", IMU_PITCH_SIGN, "sign", "+1 or -1", "bench-tune", "must match real IMU mounting"},
    {"IMU_PITCH_OFFSET_CDEG", IMU_PITCH_OFFSET_CDEG, "cdeg", "IMU calibration", "bench-tune", "zero offset from static ground attitude"},
    {"IMU_WALL_ENTER_CDEG", IMU_WALL_ENTER_CDEG, "cdeg", "IMU threshold", "bench-tune", "wall-enter hysteresis high threshold"},
    {"IMU_WALL_EXIT_CDEG", IMU_WALL_EXIT_CDEG, "cdeg", "IMU threshold", "bench-tune", "wall-exit hysteresis low threshold"},
    {"LINE_QUALITY_MIN", LINE_QUALITY_MIN, "adc_norm", "alias of LINE_LOST_QUALITY_MIN", "bench-tune", "wrong threshold causes false line loss"},
    {"FUZZY_E_SCALE", FUZZY_E_SCALE, "error_norm", "-1000..1000", "software", "wrong scale changes membership activation"},
    {"FUZZY_DE_SCALE", FUZZY_DE_SCALE, "rate_norm", "-1000..1000", "software", "wrong scale changes D damping"},
    {"FUZZY_UPDATE_PERIOD_MS", FUZZY_UPDATE_PERIOD_MS, "ms", "10 ms recommended", "software", "too fast causes gain chatter"},
    {"FUZZY_KP_SCALE", FUZZY_KP_SCALE, "gain_scale", "fixed point", "software", "must match controller math"},
    {"FUZZY_KI_SCALE", FUZZY_KI_SCALE, "gain_scale", "fixed point", "software", "must remain very small"},
    {"FUZZY_KD_SCALE", FUZZY_KD_SCALE, "gain_scale", "fixed point", "software", "must match controller math"},
    {"FUZZY_KP_MIN", FUZZY_KP_MIN, "gain", "bounded", "software", "lower bound for fuzzy result"},
    {"FUZZY_KP_MAX", FUZZY_KP_MAX, "gain", "bounded", "software", "upper bound for fuzzy result"},
    {"FUZZY_KI_MIN", FUZZY_KI_MIN, "gain", "bounded", "software", "lower bound for fuzzy result"},
    {"FUZZY_KI_MAX", FUZZY_KI_MAX, "gain", "bounded", "software", "upper bound for fuzzy result"},
    {"FUZZY_KD_MIN", FUZZY_KD_MIN, "gain", "bounded", "software", "lower bound for fuzzy result"},
    {"FUZZY_KD_MAX", FUZZY_KD_MAX, "gain", "bounded", "software", "upper bound for fuzzy result"},
    {"TRACK_MODE_DEBOUNCE_COUNT", TRACK_MODE_DEBOUNCE_COUNT, "samples", ">=1", "software", "low value causes mode chatter"},
    {"TRACK_MODE_MIN_DWELL_MS", TRACK_MODE_MIN_DWELL_MS, "ms", ">= control period", "software", "low value causes mode chatter"},
    {"STRAIGHT_BASE_KP", FUZZY_STRAIGHT_BASE_KP, "gain", "mode profile", "software", "ground straight first tuning item"},
    {"STRAIGHT_BASE_KI", FUZZY_STRAIGHT_BASE_KI, "gain", "mode profile", "software", "only tiny straight integral is allowed"},
    {"STRAIGHT_BASE_KD", FUZZY_STRAIGHT_BASE_KD, "gain", "mode profile", "software", "straight damping"},
    {"STRAIGHT_SPEED_MM_S", FUZZY_STRAIGHT_SPEED_MM_S, "mm_s", "mode profile", "software", "speed target must stay inside safety limit"},
    {"NORMAL_CURVE_BASE_KP", FUZZY_NORMAL_BASE_KP, "gain", "mode profile", "software", "curve steering gain"},
    {"NORMAL_CURVE_BASE_KI", FUZZY_NORMAL_BASE_KI, "gain", "mode profile", "software", "curve integral disabled"},
    {"NORMAL_CURVE_BASE_KD", FUZZY_NORMAL_BASE_KD, "gain", "mode profile", "software", "curve damping"},
    {"NORMAL_CURVE_SPEED_MM_S", FUZZY_NORMAL_SPEED_MM_S, "mm_s", "mode profile", "software", "speed target must stay inside safety limit"},
    {"SHARP_CURVE_BASE_KP", FUZZY_SHARP_BASE_KP, "gain", "mode profile", "software", "sharp turn gain"},
    {"SHARP_CURVE_BASE_KI", FUZZY_SHARP_BASE_KI, "gain", "mode profile", "software", "sharp turn integral disabled"},
    {"SHARP_CURVE_BASE_KD", FUZZY_SHARP_BASE_KD, "gain", "mode profile", "software", "sharp turn damping"},
    {"SHARP_CURVE_SPEED_MM_S", FUZZY_SHARP_SPEED_MM_S, "mm_s", "mode profile", "software", "reduced speed for sharp turns"},
    {"OMEGA_BASE_KP", FUZZY_OMEGA_BASE_KP, "gain", "mode profile", "software", "omega gain"},
    {"OMEGA_BASE_KI", FUZZY_OMEGA_BASE_KI, "gain", "mode profile", "software", "omega integral disabled"},
    {"OMEGA_BASE_KD", FUZZY_OMEGA_BASE_KD, "gain", "mode profile", "software", "omega damping"},
    {"OMEGA_SPEED_MM_S", FUZZY_OMEGA_SPEED_MM_S, "mm_s", "mode profile", "software", "low omega speed"},
    {"HEX_LOOP_BASE_KP", FUZZY_HEX_BASE_KP, "gain", "mode profile", "software", "hex loop gain"},
    {"HEX_LOOP_BASE_KI", FUZZY_HEX_BASE_KI, "gain", "mode profile", "software", "hex loop integral disabled"},
    {"HEX_LOOP_BASE_KD", FUZZY_HEX_BASE_KD, "gain", "mode profile", "software", "hex loop damping"},
    {"HEX_LOOP_SPEED_MM_S", FUZZY_HEX_SPEED_MM_S, "mm_s", "mode profile", "software", "medium-low hex speed"},
    {"TRANSITION_BASE_KP", FUZZY_TRANSITION_BASE_KP, "gain", "mode profile", "software", "transition gain"},
    {"TRANSITION_BASE_KI", FUZZY_TRANSITION_BASE_KI, "gain", "mode profile", "software", "transition integral disabled"},
    {"TRANSITION_BASE_KD", FUZZY_TRANSITION_BASE_KD, "gain", "mode profile", "software", "transition damping"},
    {"TRANSITION_SPEED_MM_S", FUZZY_TRANSITION_SPEED_MM_S, "mm_s", "mode profile", "software", "very low transition speed"},
    {"WALL_BASE_KP", FUZZY_WALL_BASE_KP, "gain", "mode profile", "software", "wall gain is software-only until hardware verified"},
    {"WALL_BASE_KI", FUZZY_WALL_BASE_KI, "gain", "mode profile", "software", "wall integral disabled"},
    {"WALL_BASE_KD", FUZZY_WALL_BASE_KD, "gain", "mode profile", "software", "wall damping"},
    {"WALL_SPEED_MM_S", FUZZY_WALL_SPEED_MM_S, "mm_s", "mode profile", "software", "wall speed is not a real wall permission"},
    {"CYLINDER_BASE_KP", FUZZY_CYLINDER_BASE_KP, "gain", "mode profile", "software", "curved surface gain"},
    {"CYLINDER_BASE_KI", FUZZY_CYLINDER_BASE_KI, "gain", "mode profile", "software", "curved surface integral disabled"},
    {"CYLINDER_BASE_KD", FUZZY_CYLINDER_BASE_KD, "gain", "mode profile", "software", "curved surface damping"},
    {"CYLINDER_SPEED_MM_S", FUZZY_CYLINDER_SPEED_MM_S, "mm_s", "mode profile", "software", "low curved surface speed"},
    {"SEESAW_BASE_KP", FUZZY_SEESAW_BASE_KP, "gain", "mode profile", "software", "seesaw gain"},
    {"SEESAW_BASE_KI", FUZZY_SEESAW_BASE_KI, "gain", "mode profile", "software", "seesaw integral disabled"},
    {"SEESAW_BASE_KD", FUZZY_SEESAW_BASE_KD, "gain", "mode profile", "software", "seesaw damping"},
    {"SEESAW_SPEED_MM_S", FUZZY_SEESAW_SPEED_MM_S, "mm_s", "mode profile", "software", "low seesaw speed"},
    {"RECOVERY_BASE_KP", FUZZY_RECOVERY_BASE_KP, "gain", "mode profile", "software", "recovery gain"},
    {"RECOVERY_BASE_KI", FUZZY_RECOVERY_BASE_KI, "gain", "mode profile", "software", "recovery integral disabled"},
    {"RECOVERY_BASE_KD", FUZZY_RECOVERY_BASE_KD, "gain", "mode profile", "software", "recovery damping"},
    {"RECOVERY_SPEED_MM_S", FUZZY_RECOVERY_SPEED_MM_S, "mm_s", "mode profile", "software", "low recovery speed"}
};

const app_param_entry_t *app_params_table(u16 *count)
{
    if (count != 0) {
        *count = (u16)(sizeof(g_params) / sizeof(g_params[0]));
    }
    return g_params;
}
