#ifndef COMPETITION_PROFILE_H
#define COMPETITION_PROFILE_H

/*
 * 竞赛车集中参数入口。
 * 单位和默认值说明：
 * - 速度均为 mm/s，脉宽均为 us，时间均为 ms。
 * - 当前默认值是软件起点和离地/低速验证值，不是实车完整赛道标定值。
 * - 后续调车优先只改本文件和 BSP/board_emag_map.h，避免在控制模块散落魔法数。
 */

#define LINE_DIRECTION_SIGN 1
#define LINE_WEIGHT_SCALE 1
#define LINE_VALID_SUM_MIN 160u
#define LINE_LOST_QUALITY_MIN 200u
#define LINE_FILTER_ALPHA 3
#define LINE_FILTER_DENOM 4

/* Historical servo settings are retained for old reference files only. */
#define STEERING_LEFT_CENTER_US 1510u
#define STEERING_RIGHT_CENTER_US 1510u
#define STEERING_LEFT_MIN_US 1000u
#define STEERING_LEFT_MAX_US 2000u
#define STEERING_RIGHT_MIN_US 1000u
#define STEERING_RIGHT_MAX_US 2000u
#define STEERING_LEFT_SIGN 1
#define STEERING_RIGHT_SIGN -1

#define SPEED_KP 32
#define SPEED_KI 4
#define SPEED_INTEGRAL_LIMIT 3000l
#define SPEED_OUTPUT_LIMIT 260
#define SPEED_ACCEL_LIMIT 12

#define POWER_GUARD_ENABLE 0
#define POWER_ADC_CHANNEL 0u
#define POWER_ADC_FILTER_ALPHA 3u
#define POWER_ADC_FILTER_DENOM 4u
#define POWER_LOW_RAW_THRESHOLD 1500u
#define POWER_VOLTAGE_CALIBRATION_VALID 0
#define POWER_ADC_MV_PER_COUNT_NUM 0ul
#define POWER_ADC_MV_PER_COUNT_DEN 1ul

#define APP_ARM_SOURCE_ALWAYS_FOR_BENCH 0u
#define APP_ARM_SOURCE_GO_KEY 1u
#define APP_ARM_SOURCE_UART 2u
#define APP_ARM_SOURCE APP_ARM_SOURCE_ALWAYS_FOR_BENCH
#define APP_ARM_DEBOUNCE_MS 20u

#define ENCODER_COUNTS_PER_WHEEL_REV 0L
#define WHEEL_CIRCUMFERENCE_MM 0L
#define ENCODER_SAMPLE_PERIOD_MS 1u

#define GROUND_STEERING_KP 115
#define GROUND_STEERING_KD 70
#define FUZZY_ENABLE 0

#define DIFF_TURN_SIGN 1
#define DIFF_TURN_DELTA_LIMIT_MM_S 90
#define DIFF_TARGET_SPEED_LIMIT_MM_S 260
#define DIFF_LINE_LOST_SEARCH_SPEED_MM_S 45
#define DIFF_LINE_LOST_STOP_TIME_MS 250u

#define GROUND_STRAIGHT_SPEED_MM_S 180
#define GROUND_CURVE_SPEED_MM_S 140
#define SHARP_CURVE_SPEED_MM_S 95
#define TRANSITION_SPEED_MM_S 70
#define WALL_SPEED_MM_S 80

/* Fan ESC defaults are software starting points, not real-car calibration. */
#define FAN_PWM_FREQ_HZ 50u
#define FAN_ESC_MIN_US 1000u
#define FAN_ESC_MAX_US 2000u
#define FAN_ESC_ARM_TIME_MS 2500u
#define FAN_PRECHARGE_US 1350u
#define FAN_PRECHARGE_TIME_MS 500u
#define FAN_HOLD_US 1450u
#define FAN_BOOST_US 1600u
#define FAN_BOOST_TIME_MS 300u
#define FAN_RAMP_DOWN_STEP_US 10u
#define FAN_RAMP_DOWN_PERIOD_MS 20u
#define FAN_ESC_PHYSICAL_OUTPUT_ENABLE 0
#define WALL_RUN_ENABLE 0

/* 路线事件来源：0=无自动事件，1=Host-SIL 注入，2=手动注入，3=编码器里程脚本。 */
#define ROUTE_EVENT_SOURCE_NONE 0u
#define ROUTE_EVENT_SOURCE_HOST_SIL 1u
#define ROUTE_EVENT_SOURCE_MANUAL_INJECT 2u
#define ROUTE_EVENT_SOURCE_PROGRESS_SCRIPT 3u
#define ROUTE_EVENT_SOURCE_DEFAULT ROUTE_EVENT_SOURCE_NONE

/* 里程脚本默认关闭；距离单位 mm，0 表示该事件不自动触发。 */
#define ROUTE_PROGRESS_SCRIPT_ENABLE 0
#define ROUTE_WALL_APPROACH_DISTANCE_MM 0L
#define ROUTE_WALL_EXIT_DISTANCE_MM 0L
#define ROUTE_FINISH_DISTANCE_MM 0L

#define IMU_PITCH_AXIS 0u
#define IMU_PITCH_SIGN 1
#define IMU_PITCH_OFFSET_CDEG 0
#define IMU_WALL_ENTER_CDEG 4500
#define IMU_WALL_EXIT_CDEG 2500
#define IMU_TRANSITION_CONFIRM_MS 150u
#define IMU_GROUND_CONFIRM_MS 250u
#define IMU_STALE_TIMEOUT_MS 100u

#if (LINE_DIRECTION_SIGN != 1) && (LINE_DIRECTION_SIGN != -1)
#error LINE_DIRECTION_SIGN must be +1 or -1.
#endif

#if (DIFF_TURN_SIGN != 1) && (DIFF_TURN_SIGN != -1)
#error DIFF_TURN_SIGN must be +1 or -1.
#endif

#if (STEERING_LEFT_SIGN != 1) && (STEERING_LEFT_SIGN != -1)
#error STEERING_LEFT_SIGN must be +1 or -1.
#endif

#if (STEERING_RIGHT_SIGN != 1) && (STEERING_RIGHT_SIGN != -1)
#error STEERING_RIGHT_SIGN must be +1 or -1.
#endif

#if (FUZZY_ENABLE != 0) && (FUZZY_ENABLE != 1)
#error FUZZY_ENABLE must be 0 or 1.
#endif

#if (POWER_GUARD_ENABLE != 0) && (POWER_GUARD_ENABLE != 1)
#error POWER_GUARD_ENABLE must be 0 or 1.
#endif

#if (APP_ARM_SOURCE != APP_ARM_SOURCE_ALWAYS_FOR_BENCH) && \
    (APP_ARM_SOURCE != APP_ARM_SOURCE_GO_KEY) && \
    (APP_ARM_SOURCE != APP_ARM_SOURCE_UART)
#error APP_ARM_SOURCE must be one of APP_ARM_SOURCE_*.
#endif

#if (FAN_ESC_PHYSICAL_OUTPUT_ENABLE != 0) && (FAN_ESC_PHYSICAL_OUTPUT_ENABLE != 1)
#error FAN_ESC_PHYSICAL_OUTPUT_ENABLE must be 0 or 1.
#endif

#if (WALL_RUN_ENABLE != 0) && (WALL_RUN_ENABLE != 1)
#error WALL_RUN_ENABLE must be 0 or 1.
#endif

#if (ROUTE_EVENT_SOURCE_DEFAULT != ROUTE_EVENT_SOURCE_NONE) && \
    (ROUTE_EVENT_SOURCE_DEFAULT != ROUTE_EVENT_SOURCE_HOST_SIL) && \
    (ROUTE_EVENT_SOURCE_DEFAULT != ROUTE_EVENT_SOURCE_MANUAL_INJECT) && \
    (ROUTE_EVENT_SOURCE_DEFAULT != ROUTE_EVENT_SOURCE_PROGRESS_SCRIPT)
#error ROUTE_EVENT_SOURCE_DEFAULT must be one of the ROUTE_EVENT_SOURCE_* values.
#endif

#if (ROUTE_PROGRESS_SCRIPT_ENABLE != 0) && (ROUTE_PROGRESS_SCRIPT_ENABLE != 1)
#error ROUTE_PROGRESS_SCRIPT_ENABLE must be 0 or 1.
#endif

#if (IMU_PITCH_SIGN != 1) && (IMU_PITCH_SIGN != -1)
#error IMU_PITCH_SIGN must be +1 or -1.
#endif

#if (IMU_PITCH_AXIS > 2u)
#error IMU_PITCH_AXIS must be 0, 1, or 2.
#endif

#endif
