#ifndef BOARD_MAP_H
#define BOARD_MAP_H

#define BOARD_MAP_VERIFIED 0
#define BOARD_AI8051U_CLOCK_HZ 40000000ul

#define BOARD_DEBUG_UART_RESOURCE_EVIDENCE 1
#define BOARD_DEBUG_UART_VERIFIED 1
#define BOARD_DEBUG_UART_NAME "UART1_P30_P31"

#define BOARD_DRIVE_RESOURCE_EVIDENCE 1
#define BOARD_DRIVE_VERIFIED 1
#define BOARD_DRIVE_PWM_LEFT "PWM5_P50"
#define BOARD_DRIVE_PWM_RIGHT "PWM7_P52"
#define BOARD_DRIVE_DIR_LEFT "P51"
#define BOARD_DRIVE_DIR_RIGHT "P53"

#define BOARD_STEERING_RESOURCE_EVIDENCE 1
#define BOARD_STEERING_VERIFIED 0
#define BOARD_STEERING_PWM1 "HISTORICAL_PWM1_P10_INACTIVE"
#define BOARD_STEERING_PWM2 "HISTORICAL_PWM2_P12_INACTIVE"

#define BOARD_SUCTION_SIGNAL_EVIDENCE 0
#define BOARD_SUCTION_SIGNAL_VERIFIED 0
#define BOARD_SUCTION_PWM_CANDIDATE "HISTORICAL_PWM2N_P23_INACTIVE"

#define BOARD_FAN_ESC_SIGNAL_MAPPED 1
#define BOARD_FAN_ESC_BENCH_VERIFIED 0
#define BOARD_FAN_PWM_MAPPED BOARD_FAN_ESC_SIGNAL_MAPPED
#define BOARD_FAN_ESC_SIGNAL_VERIFIED BOARD_FAN_ESC_BENCH_VERIFIED
#define BOARD_FAN_ESC_PWM "P2.2_PWM2P_3"

#define BOARD_ENCODER_RESOURCE_EVIDENCE 1
#define BOARD_ENCODER_VERIFIED 1
#define BOARD_ENCODER1_A "P04_T3"
#define BOARD_ENCODER1_DIR "P05"
#define BOARD_ENCODER2_A "P06_T4"
#define BOARD_ENCODER2_DIR "P07"

#define BOARD_EMAG_ADC_RESOURCE_EVIDENCE 1
#define BOARD_EMAG_ADC_VERIFIED 0
#define BOARD_IMU_BUS_RESOURCE_EVIDENCE 1
#define BOARD_IMU_BUS_VERIFIED 0
#define BOARD_POWER_SENSE_VERIFIED 0
#define BOARD_UI_RESOURCE_EVIDENCE 1
#define BOARD_UI_VERIFIED 0

#endif
